### ISSUE TITLE
Should <center-block> work for lists?

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#28]
We've been using <center-block> for lists on objectives and recap pages to center them, but I just realized it's broken in IE at smaller screen sizes (the text won't wrap, it just goes off the edges).

For now I'm going back to the old fashioned way of centering a list. Should <center-block> be used for anything other than a short sentence?

**Comment by ivyreese** [comment]
There might be an ugly hack workaround along the lines of...

``` html
<div class="center-block-hack">
    <div>My short thing.</div><br>
    <div>My other short thing.</div><br>
</div>
```

``` scss
.center-block-hack {
    text-align: center;

    & > * {
        display: inline-block;
        text-align: left;
    }
}
```

As for what to do with the real <center-block> thingy.. it was a bit of a hack to begin with. So if it doesn't work for something, then that's the limit, I guess. There might be ways to do it better, but I can't think of anything offhand.

**Comment by crystalrubik** [comment]
Ok, but I'd still want the bullets that come with the list. This is my hack...

``` scss
ul {
        display: block;
        max-width: 30em;
        margin: 1em auto 0;
    }
```

Seems to work. Have to sort of guesstimate the max-width as each list is a different width.
