### ISSUE TITLE
[hide-loading] script

### ISSUE THREAD

**Issue by ivyreese** [cdig/cd-module#57]
I'd be nice to have a `hide-loading` attribute that will be hidden by CSS until the page is loaded.

Perhaps, the script can add a [dom-content-loaded] attribute to the HTML element after loading has finished, and the hide-loading CSS can be like..

``` css
html:not([dom-content-loaded]) [hide-loading] {
    display: none!important; // Or visibility: hidden ??
}
```

It might be nice to figure out some way to show a loading indicator in place of these things? Perhaps, using pseudo elements?
